// Every mood is a pool of tracks with an album cover (`art`) for its tile.
// A mood with a `lead` always shows that track first.
// The app draws five at a time from the pool.
const MOODS = [
  {
    id: "heartbroken",
    art: "Take Care",
    name: "Trust Issues",
    line: "I'm just sayin' you could do better.",
    tracks: [
      { title: "Marvins Room", album: "Take Care", year: 2011, why: "The 3am phone call you shouldn't make, in song form." },
      { title: "Doing It Wrong", album: "Take Care", year: 2011, why: "Stevie Wonder on harmonica while you both admit it's done." },
      { title: "Jaded", album: "Scorpion", year: 2018, why: "Slow, bitter, and a little too honest about who left who." },
      { title: "Fire & Desire", album: "Views", year: 2016, why: "Wanting someone you know you can't have back." },
      { title: "Shot for Me", album: "Take Care", year: 2011, why: "Toasting the people who moved on before you did." },
      { title: "From Time", album: "Nothing Was the Same", year: 2013, why: "Jhené Aiko asks the questions you've been avoiding." },
      { title: "Karaoke", album: "Thank Me Later", year: 2010, why: "Track two on the first album, and it's already a breakup." },
      { title: "Texts Go Green", album: "Honestly, Nevermind", year: 2022, why: "Blocked, dancing anyway." },
      { title: "Hours in Silence", album: "Her Loss", year: 2022, why: "Nearly seven minutes of overthinking set to a slow drum." },
      { title: "Sooner Than Later", album: "So Far Gone", year: 2009, why: "Early, raw, and already sad about someone." },
      { title: "U with Me?", album: "Views", year: 2016, why: "Reading old messages and asking a question you know the answer to." },
      { title: "Nothings into Somethings", album: "More Life", year: 2017, why: "Finding out from someone else that they moved on." },
      { title: "Keep the Family Close", album: "Views", year: 2016, why: "The album opens with strings and a list of friends he doesn't have anymore." },
      { title: "Redemption", album: "Views", year: 2016, why: "Five minutes of guilt over a beat that never lifts." },
      { title: "Finesse", album: "Scorpion", year: 2018, why: "Wanting someone who's already with someone. Quiet about it." },
      { title: "Pipe Down", album: "Certified Lover Boy", year: 2021, why: "The angriest three minutes on Certified Lover Boy." },
      { title: "Falling Back", album: "Honestly, Nevermind", year: 2022, why: "House drums under a chorus about being let down again." },
      { title: "Tried Our Best", album: "For All the Dogs", year: 2023, why: "The closest thing to closure on For All the Dogs." },
      { title: "Feel No Ways", album: "Views", year: 2016, why: "Moving on, over a beat that makes it sound almost like a party." },
      { title: "Stuck", album: "Maid of Honour", year: 2026, why: "From the toxic-romance side of the 2026 triple drop." }
    ]
  },
  {
    id: "hyped",
    art: "Scorpion",
    name: "0 to 100",
    line: "I was runnin' through the 6 with my woes.",
    tracks: [
      { title: "Nonstop", album: "Scorpion", year: 2018, why: "Tay Keith beat, no chorus needed." },
      { title: "Energy", album: "If You're Reading This It's Too Late", year: 2015, why: "Every line is a threat you can shout along to." },
      { title: "0 to 100 / The Catch Up", album: "Single", year: 2014, why: "The first half of this song is a whole workout." },
      { title: "Headlines", album: "Take Care", year: 2011, why: "Boi-1da drums and the horn that ends every set." },
      { title: "Know Yourself", album: "If You're Reading This It's Too Late", year: 2015, why: "Running through the 6 with your woes." },
      { title: "Over", album: "Thank Me Later", year: 2010, why: "Strings, drums, and a young rapper who knows he made it." },
      { title: "Rich Flex", album: "Her Loss", year: 2022, why: "21, can you do something for me?" },
      { title: "Worst Behavior", album: "Nothing Was the Same", year: 2013, why: "Loud, petty, and perfect at full volume." },
      { title: "First Person Shooter", album: "For All the Dogs", year: 2023, why: "Two rappers in a good mood taking turns going off." },
      { title: "Way 2 Sexy", album: "Certified Lover Boy", year: 2021, why: "The Right Said Fred sample nobody asked for and everybody yells." },
      { title: "Jumbotron Shit Poppin", album: "Her Loss", year: 2022, why: "Pure momentum from the first bar." },
      { title: "HYFR (Hell Ya Fucking Right)", album: "Take Care", year: 2011, why: "Lil Wayne, a bar mitzvah video, and a hook you can't say quietly." },
      { title: "10 Bands", album: "If You're Reading This It's Too Late", year: 2015, why: "Counting money with the blinds closed." },
      { title: "Portland", album: "More Life", year: 2017, why: "Quavo, Travis Scott, and the flute beat." },
      { title: "Knife Talk", album: "Certified Lover Boy", year: 2021, why: "21 Savage and Project Pat on the hardest beat on the album." },
      { title: "Jimmy Cooks", album: "Honestly, Nevermind", year: 2022, why: "A house album ends with 21 Savage and a beat switch." },
      { title: "IDGAF", album: "For All the Dogs", year: 2023, why: "Yeat feature. Sounds like the ceiling is caving in, on purpose." },
      { title: "Janice STFU", album: "Iceman", year: 2026, why: "The 'I Follow Rivers' flip that debuted at number one." },
      { title: "Rich Baby Daddy", album: "For All the Dogs", year: 2023, why: "Sexyy Red and SZA on the loudest song on For All the Dogs." }
    ]
  },
  {
    id: "late-night",
    art: "Honestly, Nevermind",
    name: "Hotline Bling",
    line: "You used to call me on my cell phone, late night when you need my love.",
    tracks: [
      { title: "Passionfruit", album: "More Life", year: 2017, why: "Tropical house for a long-distance situation." },
      { title: "Teenage Fever", album: "More Life", year: 2017, why: "The Jennifer Lopez sample makes the whole room slow down." },
      { title: "Massive", album: "Honestly, Nevermind", year: 2022, why: "A club track for when the club has emptied out." },
      { title: "Controlla", album: "Views", year: 2016, why: "Dancehall pace, whispered vocals." },
      { title: "Jungle", album: "If You're Reading This It's Too Late", year: 2015, why: "Are we still good? asked over a Gabriel Garzón-Montano loop." },
      { title: "Come Thru", album: "Nothing Was the Same", year: 2013, why: "The text you send at 1am, produced by Noah '40' Shebib." },
      { title: "Cameras / Good Ones Go Interlude", album: "Take Care", year: 2011, why: "Two songs that drift into each other like a late drive." },
      { title: "Chicago Freestyle", album: "Dark Lane Demo Tapes", year: 2020, why: "Eminem flip, hotel room, city outside the window." },
      { title: "After Dark", album: "Scorpion", year: 2018, why: "Ty Dolla $ign and Static Major on a slow burner." },
      { title: "The Motion", album: "Single", year: 2013, why: "Sampha on the hook, everything else stays out of the way. Collected on Care Package in 2019." },
      { title: "Connect", album: "Nothing Was the Same", year: 2013, why: "Houston-slow, screwed vocals, a beat that barely moves." },
      { title: "Sticky", album: "Honestly, Nevermind", year: 2022, why: "House drums for the last hour of the night." },
      { title: "Crew Love", album: "Take Care", year: 2011, why: "The Weeknd on the hook, the whole city awake." },
      { title: "Hotline Bling", album: "Views", year: 2016, why: "The Timmy Thomas loop and the dancing you already know." },
      { title: "Too Much", album: "Nothing Was the Same", year: 2013, why: "Sampha's piano and a verse about his family." },
      { title: "Faithful", album: "Views", year: 2016, why: "Pimp C and dvsn on a song that moves at walking pace." },
      { title: "Spin Bout U", album: "Her Loss", year: 2022, why: "The soft one on Her Loss." },
      { title: "Time Flies", album: "Dark Lane Demo Tapes", year: 2020, why: "Driving to someone's place at 3am and knowing better." },
      { title: "Healing", album: "Diamante", year: 2024, why: "Gordo's house beat with Drake singing over it. Made for 2am." },
      { title: "Don't Matter to Me", album: "Scorpion", year: 2018, why: "Unreleased Michael Jackson vocals on a song about a bad night." },
      { title: "Flight's Booked", album: "Honestly, Nevermind", year: 2022, why: "Leaving town in the morning, staying out tonight." },
      { title: "Girls Want Girls", album: "Certified Lover Boy", year: 2021, why: "Lil Baby feature, slow drums, the club near closing." }
    ]
  },
  {
    id: "petty",
    art: "Family Matters",
    name: "Twitter Fingers",
    line: "Trigger fingers turn to Twitter fingers.",
    tracks: [
      { title: "Back to Back", album: "Single", year: 2015, why: "The diss track that got a Grammy nomination." },
      { title: "Push Ups", album: "Single", year: 2024, why: "Measuring everyone's shoe size and contracts." },
      { title: "Family Matters", album: "Single", year: 2024, why: "Seven minutes, three beats, no one spared." },
      { title: "Duppy Freestyle", album: "Single", year: 2018, why: "Sends an invoice at the end. Actually sends it." },
      { title: "Two Birds, One Stone", album: "Single", year: 2016, why: "Quiet, calm, and aimed at two people at once." },
      { title: "The Language", album: "Nothing Was the Same", year: 2013, why: "I don't know why they been lying, but your shit is not that inspiring." },
      { title: "Mob Ties", album: "Scorpion", year: 2018, why: "Fake friends, real consequences." },
      { title: "Fake Love", album: "More Life", year: 2017, why: "For the people who only call when it's going well." },
      { title: "Star67", album: "If You're Reading This It's Too Late", year: 2015, why: "Calling from a blocked number, half laughing." },
      { title: "No Friends in the Industry", album: "Certified Lover Boy", year: 2021, why: "Says exactly what the title says." },
      { title: "Childs Play", album: "Views", year: 2016, why: "Arguing at the Cheesecake Factory, immortalised." },
      { title: "7AM on Bridle Path", album: "Certified Lover Boy", year: 2021, why: "A timestamp track with a specific target." },
      { title: "Summer Sixteen", album: "Single", year: 2016, why: "Looking for revenge, all summer sixteen." },
      { title: "Diplomatic Immunity", album: "Scary Hours", year: 2018, why: "No hook, four minutes, everybody's name comes up." },
      { title: "I'm Upset", album: "Scorpion", year: 2018, why: "The Degrassi reunion video. The song is about the money." },
      { title: "Can't Take a Joke", album: "Scorpion", year: 2018, why: "For when they can't." },
      { title: "Circo Loco", album: "Her Loss", year: 2022, why: "The Daft Punk flip, and the verse everyone argued about." },
      { title: "Fear of Heights", album: "For All the Dogs", year: 2023, why: "Bitter, short, and about someone specific." },
      { title: "Slime You Out", album: "For All the Dogs", year: 2023, why: "SZA and Drake taking turns being unfair to each other." }
    ]
  },
  {
    id: "nostalgic",
    art: "Thank Me Later",
    name: "Weston Road",
    line: "Look what you've done, look what you've done for me.",
    tracks: [
      { title: "Look What You've Done", album: "Take Care", year: 2011, why: "A thank-you letter to his mum, uncle, and grandmother." },
      { title: "Best I Ever Had", album: "So Far Gone", year: 2009, why: "Where it started for most people." },
      { title: "Successful", album: "So Far Gone", year: 2009, why: "Trey Songz, Lil Wayne, and a rapper who hadn't made it yet." },
      { title: "Houstatlantavegas", album: "So Far Gone", year: 2009, why: "The mixtape song that sounds like a memory." },
      { title: "Say What's Real", album: "So Far Gone", year: 2009, why: "Rapping over a Kanye beat about being nervous." },
      { title: "November 18th", album: "So Far Gone", year: 2009, why: "Screwed Houston homage from before Houston claimed him." },
      { title: "Find Your Love", album: "Thank Me Later", year: 2010, why: "Kanye on the boards, a chorus everyone knows." },
      { title: "You & the 6", album: "If You're Reading This It's Too Late", year: 2015, why: "A conversation with his mother about the city." },
      { title: "Weston Road Flows", album: "Views", year: 2016, why: "Mary J. Blige sample, Toronto street names, no hook." },
      { title: "Do Not Disturb", album: "More Life", year: 2017, why: "Closing the door on a chapter and saying so." },
      { title: "Fancy", album: "Thank Me Later", year: 2010, why: "Swizz Beatz, T.I., and a chorus for your best friends." },
      { title: "Uptown", album: "So Far Gone", year: 2009, why: "Bun B and Lil Wayne on the first track that felt like Toronto." },
      { title: "Lust for Life", album: "So Far Gone", year: 2009, why: "The first thing you hear on So Far Gone." },
      { title: "The Calm", album: "So Far Gone", year: 2009, why: "Recorded before anything was certain. Sounds like it." },
      { title: "Miss Me", album: "Thank Me Later", year: 2010, why: "Lil Wayne on the hook, Drake still new to all of it." },
      { title: "Thank Me Now", album: "Thank Me Later", year: 2010, why: "The last song on the first album, already looking back." },
      { title: "Wu-Tang Forever", album: "Nothing Was the Same", year: 2013, why: "An 'It's Yourz' sample and a song that isn't really about Wu-Tang." },
      { title: "Views", album: "Views", year: 2016, why: "The title track, Toronto in winter, right before Hotline Bling." }
    ]
  },
  {
    id: "confident",
    art: "The Best in the World Pack",
    name: "6 God",
    line: "I know I said top five, but I'm top two.",
    tracks: [
      { title: "God's Plan", album: "Scorpion", year: 2018, why: "The biggest song he has, and it still feels calm." },
      { title: "Nice for What", album: "Scorpion", year: 2018, why: "Lauryn Hill sample, bounce drums, main character energy." },
      { title: "Tuscan Leather", album: "Nothing Was the Same", year: 2013, why: "Six minutes of rapping with no hook to hide behind." },
      { title: "Pound Cake / Paris Morton Music 2", album: "Nothing Was the Same", year: 2013, why: "Jay-Z shows up and Drake still wins the song." },
      { title: "Champagne Poetry", album: "Certified Lover Boy", year: 2021, why: "The Beatles sample and the best verse on the album." },
      { title: "The Motto", album: "Take Care", year: 2011, why: "Gave the world YOLO. Never apologised." },
      { title: "Gyalchester", album: "More Life", year: 2017, why: "I know I said top five, but I'm top two." },
      { title: "Laugh Now Cry Later", album: "Single", year: 2020, why: "Lil Durk feature, Nike campus video, pure ease." },
      { title: "Under Ground Kings", album: "Take Care", year: 2011, why: "The Take Care track for people who want bars." },
      { title: "Elevate", album: "Scorpion", year: 2018, why: "Short, clean, and sure of itself." },
      { title: "6 God", album: "If You're Reading This It's Too Late", year: 2015, why: "Boi-1da drums and a title he gave himself." },
      { title: "Still Here", album: "Views", year: 2016, why: "Two minutes of reminding you." },
      { title: "Free Smoke", album: "More Life", year: 2017, why: "The opener. Sounds like walking into a room you paid for." },
      { title: "Sandra's Rose", album: "Scorpion", year: 2018, why: "A DJ Premier beat and a verse that earns it." },
      { title: "Fair Trade", album: "Certified Lover Boy", year: 2021, why: "Losing friends and finding peace, with Travis Scott." },
      { title: "What's Next", album: "Scary Hours 2", year: 2021, why: "The 2021 reset. Short, sure, over in three minutes." },
      { title: "National Treasures", album: "Iceman", year: 2026, why: "Toronto, the Raptors, and the line about the Iceman being a nice man." }
    ]
  },
  {
    id: "made-it",
    art: "Nothing Was the Same",
    name: "Now We're Here",
    line: "Started from the bottom, now we're here.",
    lead: "No Secret",
    tracks: [
      { title: "No Secret", album: "God Did", year: 2022, why: "A DJ Khaled beat and a verse that doesn't hide anything. Start here." },
      { title: "Started From the Bottom", album: "Nothing Was the Same", year: 2013, why: "The obvious one. Still works every time." },
      { title: "Trophies", album: "Young Money: Rise of an Empire", year: 2014, why: "Hit-Boy horns for when you don't need the award." },
      { title: "Money in the Grave", album: "The Best in the World Pack", year: 2019, why: "Dropped the day after the Raptors won the title. Sounds like it." },
      { title: "Legend", album: "If You're Reading This It's Too Late", year: 2015, why: "Opens the tape by telling you what he'll be when he's gone." },
      { title: "All Me", album: "Nothing Was the Same", year: 2013, why: "2 Chainz and Big Sean on a song about whose work it was." },
      { title: "Away from Home", album: "For All the Dogs", year: 2023, why: "A long look back at how far the drive was." },
      { title: "Wants and Needs", album: "Scary Hours 2", year: 2021, why: "Lil Baby feature and a list of what's already handled." },
      { title: "Lemon Pepper Freestyle", album: "Scary Hours 2", year: 2021, why: "Rick Ross, a Sunday-morning beat, and six minutes of grown-man flex." },
      { title: "Major Distribution", album: "Her Loss", year: 2022, why: "21 Savage and Drake reading the numbers out loud." },
      { title: "Glow", album: "More Life", year: 2017, why: "Kanye on the hook. About watching each other shine." },
      { title: "Sacrifices", album: "More Life", year: 2017, why: "2 Chainz and Young Thug on what it cost to get here." },
      { title: "Pop Style", album: "Views", year: 2016, why: "Slow, heavy, and completely sure of the outcome." },
      { title: "Dreams Money Can Buy", album: "Single", year: 2011, why: "The 2011 loosie about the things you can finally afford. Collected on Care Package." },
      { title: "Papi's Home", album: "Certified Lover Boy", year: 2021, why: "Back in the building, and letting the building know." },
      { title: "Talk Up", album: "Scorpion", year: 2018, why: "DJ Premier scratches, a Jay-Z verse, and no doubt in the room." },
      { title: "War", album: "Dark Lane Demo Tapes", year: 2020, why: "UK drill from Toronto, about the people who came up with him." }
    ]
  },
  {
    id: "in-love",
    art: "Certified Lover Boy",
    name: "Lover Boy",
    line: "Just hold on, we're going home.",
    tracks: [
      { title: "Hold On, We're Going Home", album: "Nothing Was the Same", year: 2013, why: "The wedding song. It earned it." },
      { title: "Take Care", album: "Take Care", year: 2011, why: "Rihanna, Jamie xx, and a promise to try again." },
      { title: "One Dance", album: "Views", year: 2016, why: "Wizkid and Kyla on the song that took over a summer." },
      { title: "Too Good", album: "Views", year: 2016, why: "Rihanna again, both of them a little too honest." },
      { title: "Make Me Proud", album: "Take Care", year: 2011, why: "Nicki Minaj on a song that's genuinely proud of someone." },
      { title: "Get It Together", album: "More Life", year: 2017, why: "Jorja Smith and a Black Coffee beat. Slow, warm." },
      { title: "In My Feelings", album: "Scorpion", year: 2018, why: "Kiki, do you love me? Asked earnestly." },
      { title: "Fountains", album: "Certified Lover Boy", year: 2021, why: "Tems on the hook and an Afrobeats sway." },
      { title: "Search & Rescue", album: "Single", year: 2023, why: "Asking someone to pull him out of his lifestyle, with a Kim Kardashian clip in the middle." },
      { title: "Shut It Down", album: "Thank Me Later", year: 2010, why: "Almost seven minutes with The-Dream about someone who stops the room." },
      { title: "Nokia", album: "$ome $exy $ongs 4 U", year: 2025, why: "The phone-ringing beat that took over 2025." },
      { title: "Race My Mind", album: "Certified Lover Boy", year: 2021, why: "The song that runs while you wait for a reply." },
      { title: "Own It", album: "Nothing Was the Same", year: 2013, why: "The one about wanting more than the arrangement." },
      { title: "Practice", album: "Take Care", year: 2011, why: "Back That Azz Up, slowed down and made sincere." },
      { title: "With You", album: "Views", year: 2016, why: "PartyNextDoor on a hook that sways." },
      { title: "Summer Games", album: "Scorpion", year: 2018, why: "Eighties synths and a summer that ended too fast." },
      { title: "Blem", album: "More Life", year: 2017, why: "Blem means high. The song means honest." },
      { title: "TSU", album: "Certified Lover Boy", year: 2021, why: "Slow, warm, and a little too aware of itself." },
      { title: "Die Trying", album: "$ome $exy $ongs 4 U", year: 2025, why: "Yebba on the hook. The most sincere song on the album." },
      { title: "Greece", album: "Single", year: 2020, why: "A DJ Khaled beat that sounds like a holiday, about exactly that." },
      { title: "Whisper My Name", album: "Iceman", year: 2026, why: "The softest moment on Iceman." }
    ]
  },
  {
    id: "grinding",
    art: "If You're Reading This It's Too Late",
    name: "Nonstop",
    line: "Working on the weekend like usual.",
    tracks: [
      { title: "Light Up", album: "Thank Me Later", year: 2010, why: "Jay-Z passes the torch and Drake sounds ready." },
      { title: "Over My Dead Body", album: "Take Care", year: 2011, why: "Chantal Kreviazuk piano and a mission statement." },
      { title: "Lord Knows", album: "Take Care", year: 2011, why: "Just Blaze choir, Rick Ross, and no room for doubt." },
      { title: "Furthest Thing", album: "Nothing Was the Same", year: 2013, why: "Somewhere between being famous and staying focused." },
      { title: "6PM in New York", album: "If You're Reading This It's Too Late", year: 2015, why: "A timestamp track that reads like a to-do list." },
      { title: "5AM in Toronto", album: "Single", year: 2013, why: "The early one. All bars, no chorus. Collected on Care Package in 2019." },
      { title: "8AM in Charlotte", album: "For All the Dogs", year: 2023, why: "Conductor Williams beat, ten years later, still up early." },
      { title: "Emotionless", album: "Scorpion", year: 2018, why: "Mariah Carey sample and the line about the son." },
      { title: "The Resistance", album: "Thank Me Later", year: 2010, why: "What happens to the people you leave behind on the way up." },
      { title: "Survival", album: "Scorpion", year: 2018, why: "The album opener that takes stock of the career." },
      { title: "Fireworks", album: "Thank Me Later", year: 2010, why: "The first song on the first album. Alicia Keys on the hook." },
      { title: "Deep Pockets", album: "Dark Lane Demo Tapes", year: 2020, why: "Late-career Drake still talking about the work." },
      { title: "Lose You", album: "More Life", year: 2017, why: "Five minutes on what it costs to stay on top." },
      { title: "Can't Have Everything", album: "More Life", year: 2017, why: "Ends with a voicemail from his mum. Worth waiting for." },
      { title: "4PM in Calabasas", album: "Single", year: 2016, why: "The 2016 timestamp. Collected on Care Package in 2019." },
      { title: "When to Say When", album: "Dark Lane Demo Tapes", year: 2020, why: "Rapping over the Song Cry beat about knowing when to stop." },
      { title: "The Remorse", album: "Certified Lover Boy", year: 2021, why: "The album closer, taking stock of everyone who helped." },
      { title: "Is There More", album: "Scorpion", year: 2018, why: "The question at the end of the A side." },
      { title: "Don't Worry", album: "Iceman", year: 2026, why: "Deep in the back half of Iceman, when the dust has settled." }
    ]
  }
];
